export const projects = [
  {
    id: 1,
    title: "Ghibli landing (WIP)",
    des: "A showcase project designed to highlight the work of a renowned animation studio, focusing on immersive animations, smooth transitions, responsive design, and interactive elements.",
    keywords: [
      "Next.js",
      "Tailwind CSS",
      "TypeScript",
      "GSAP",
      "Threejs",
      "Shadcn",
    ],
    highlights: [
      "Custom-built creative design",
      "Smooth section transitions",
      "WebGPU ripple effects",
      "Fully responsive design",
      "Optimized performance",
    ],
    image: "/images/ghibli-landing.webp",
    demo: "https://landing-lime-one.vercel.app/",
  },
  {
    id: 2,
    title: "GPGPPU Particles",
    des: "A showcase project designed to highlight the work of a renowned animation studio, focusing on immersive animations, smooth transitions, responsive design, and interactive elements.",
    keywords: ["Next.js", "TypeScript", "Threejs", "Blender"],
    highlights: [
      "Custom-built creative design",
      "Smooth section transitions",
      "WebGPU ripple effects",
      "Fully responsive design",
      "Optimized performance",
    ],
    image: "/images/particles-morphing.webp",
    demo: "https://particles-morphing-tau.vercel.app/new",
  },
  {
    id: 3,
    title: "Ghibli landing (WIP)",
    des: "A showcase project designed to highlight the work of a renowned animation studio, focusing on immersive animations, smooth transitions, responsive design, and interactive elements.",
    keywords: ["Next.js", "Tailwind CSS", "TypeScript", "GSAP", "Threejs"],
    highlights: [
      "Custom-built creative design",
      "Smooth section transitions",
      "WebGPU ripple effects",
      "Fully responsive design",
      "Optimized performance",
    ],
    image: "/images/projects/ghibli-landing.png",
    demo: "https://landing-lime-one.vercel.app/",
  },
  {
    id: 4,
    title: "Ghibli landing (WIP)",
    des: "A showcase project designed to highlight the work of a renowned animation studio, focusing on immersive animations, smooth transitions, responsive design, and interactive elements.",
    keywords: [
      "Next.js",
      "Tailwind CSS",
      "TypeScript",
      "GSAP",
      "Threejs",
      "ReactThree",
    ],
    highlights: [
      "Custom-built creative design",
      "Smooth section transitions",
      "WebGPU ripple effects",
      "Fully responsive design",
      "Optimized performance",
    ],
    image: "/images/projects/ghibli-landing.png",
    demo: "https://landing-lime-one.vercel.app/",
  },
];
