export const projects = [
  {
    id: 1,
    title: "Ghibli landing",
    des: "A showcase project designed to highlight the work of a renowned animation studio, focusing on immersive animations, smooth transitions, responsive design, and interactive elements.",
    keywords: [
      "Next.js",
      "Tailwind CSS",
      "TypeScript",
      "GSAP",
      "Threejs",
      "Shadcn",
    ],
    highlights: [
      "Custom-built creative design",
      "Smooth section transitions",
      "WebGPU ripple effects",
      "Fully responsive design",
      "Optimized performance",
    ],
    image: "/images/ghibli-landing.webp",
    demo: "https://landing-lime-one.vercel.app/",
  },
  {
    id: 2,
    title: "Wolvesville AI (wip)",
    des: "A real-time social deduction game where players secretly become villagers or werewolves. Through strategic discussion, voting, and unique abilities, villagers must identify the werewolves before being outnumbered, while werewolves attempt to remain hidden and eliminate the village.",
    keywords: [
      "Cursor",
      "ReactJs",
      "Tailwind CSS",
      "TypeScript",
      "Zustand",
      "SocketIO",
      "Expressjs",
      "PostgreSQL",
    ],
    highlights: [
      "Custom-built creative design",
      "Smooth section transitions",
      "WebGPU ripple effects",
      "Fully responsive design",
      "Optimized performance",
    ],
    image: "/images/wolf-face.webp",
    demo: "https://github.com/tiennguyen00/wolvesville-ai",
  },
  {
    id: 3,
    title: "Ollama assistant",
    des: "A simple assistant that uses LLM to answer questions and express emotions using OpenAI's GPT-4o, TTS model api and PixiJS for 3D character animation.",
    keywords: ["Next.js", "PixiJS", "OpenAI", "Firebase", "TypeScript"],
    highlights: [
      "Custom-built creative design",
      "Smooth section transitions",
      "WebGPU ripple effects",
      "Fully responsive design",
      "Optimized performance",
    ],
    image: "/images/assistant.webp",
    demo: "https://ollama-assistant.vercel.app/",
  },
  {
    id: 4,
    title: "GPGPPU Particles",
    des: "Showcases an interactive particle system that morphs and responds to 3D model animations. Particles are controlled by GPU-accelerated shaders, creating fluid and organic animations that follow the movement of 3D models.",
    keywords: ["Next.js", "TypeScript", "Threejs", "Blender"],
    highlights: [
      "Custom-built creative design",
      "Smooth section transitions",
      "WebGPU ripple effects",
      "Fully responsive design",
      "Optimized performance",
    ],
    image: "/images/particles-morphing.webp",
    demo: "https://particles-morphing-tau.vercel.app/new",
  },
];
